dependencies {
    api project(':gear4jtest-core')

    implementation 'org.springframework:spring-context:6.2.8'

    testImplementation platform('org.junit:junit-bom:5.12.2')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testImplementation 'org.assertj:assertj-core:3.27.3'
    testImplementation 'org.springframework:spring-test:6.2.8'
}

ext.moduleName = 'io.test.gear4jtest.spring'
