[versions]
junit = "5.12.2"
junit-platform = "1.12.2"
slf4j = "2.0.17"
assertj = "3.27.3"
logback = "1.5.38"
mockito = "5.17.0"
micrometer = "1.15.1"
spring-boot = "3.5.3"
jackson = "2.21.5"
postgresql = "42.7.7"
mysql = "9.7.0"
mariadb = "3.5.9"
ojdbc11 = "23.26.2.0.0"
h2 = "2.4.240"
testcontainers = "1.21.4"
spring-framework = "6.2.8"
eclipse-jdt-core = "3.43.0"
eclipse-text = "3.14.400"

[libraries]
slf4j = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
jackson = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson" }
junit = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher", version.ref = "junit-platform" }
assertj = { module = "org.assertj:assertj-core", version.ref = "assertj" }
logback = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
mockito = { module = "org.mockito:mockito-core", version.ref = "mockito" }
mockito-junit = { module = "org.mockito:mockito-junit-jupiter", version.ref = "mockito" }
postgresql = { module = "org.postgresql:postgresql", version.ref = "postgresql" }
mysql = { module = "com.mysql:mysql-connector-j", version.ref = "mysql" }
mariadb = { module = "org.mariadb.jdbc:mariadb-java-client", version.ref = "mariadb" }
ojdbc11 = { module = "com.oracle.database.jdbc:ojdbc11", version.ref = "ojdbc11" }
h2 = { module = "com.h2database:h2", version.ref = "h2" }
testcontainers-junit-jupiter = { module = "org.testcontainers:junit-jupiter", version.ref = "testcontainers" }
testcontainers-postgresql = { module = "org.testcontainers:postgresql", version.ref = "testcontainers" }
testcontainers-mysql = { module = "org.testcontainers:mysql", version.ref = "testcontainers" }
testcontainers-mariadb = { module = "org.testcontainers:mariadb", version.ref = "testcontainers" }
testcontainers-oracle-xe = { module = "org.testcontainers:oracle-xe", version.ref = "testcontainers" }
micrometer = { module = "io.micrometer:micrometer-core", version.ref = "micrometer" }
spring-boot-autoconfigure = { module = "org.springframework.boot:spring-boot-autoconfigure", version.ref = "spring-boot" }
spring-boot-test = { module = "org.springframework.boot:spring-boot-test", version.ref = "spring-boot" }
spring-test = { module = "org.springframework:spring-test", version.ref = "spring-framework" }
spring-context = { module = "org.springframework:spring-context", version.ref = "spring-framework" }
spring-boot-configuration-processor = { module = "org.springframework.boot:spring-boot-configuration-processor", version.ref = "spring-boot" }
spring-boot-starter-validation = { module = "org.springframework.boot:spring-boot-starter-validation", version.ref = "spring-boot" }
spring-boot-actuator = { module = "org.springframework.boot:spring-boot-actuator", version.ref = "spring-boot" }
eclipse-jdt-core = { module = "org.eclipse.jdt:org.eclipse.jdt.core", version.ref = "eclipse-jdt-core" }
eclipse-text = { module = "org.eclipse.platform:org.eclipse.text", version.ref = "eclipse-text" }
