dependencies {
    implementation project(':gear4jtest-core')
    implementation project(':gear4jtest-external-api')
    implementation project(':gear4jtest-xml')

    testImplementation gradleTestKit()
    testImplementation(libraries.junit)
    testRuntimeOnly(libraries.junitPlatformLauncher)
    testImplementation(libraries.assertj)
}

gradlePlugin {
    plugins {
        create("gear4jXmlAssemblyLineGenerator") {
            id = "io.github.gear4jtest.xml2java"
            implementationClass = "io.github.gear4jtest.xml2java.XmlAssemblyLineGeneratorPlugin"
        }
        create("gear4jXmlAssemblyLineGeneratorLegacy") {
            id = "io.github.gear4jtest.gradle.xml2java"
            implementationClass = "io.github.gear4jtest.xml2java.XmlAssemblyLineGeneratorPlugin"
        }
    }
}

ext.moduleName = 'io.github.gear4jtest.gradle.xml2java'
