dependencies {
    api project(':gear4jtest-spring')
    implementation project(':gear4jtest-micrometer')
    implementation libs.spring.boot.autoconfigure
    implementation libs.spring.boot.starter.validation
    compileOnly libs.spring.boot.actuator

    annotationProcessor libs.spring.boot.configuration.processor

    testImplementation libs.spring.boot.test
    testImplementation libs.spring.test
    testImplementation libs.spring.boot.actuator
}

ext.moduleName = 'io.github.gear4jtest.spring.boot.starter'
