dependencies {
    api project(':gear4jtest-spring')
    api project(':gear4jtest-jdbc')
    api libs.spring.jdbc
    implementation project(':gear4jtest-micrometer')
    implementation libs.spring.boot.autoconfigure
    implementation libs.spring.boot.starter.validation
    compileOnlyApi libs.spring.boot.actuator

    annotationProcessor libs.spring.boot.configuration.processor

    testImplementation libs.spring.boot.test
    testImplementation libs.spring.test
    testImplementation libs.spring.boot.actuator
    testImplementation libs.h2
    testImplementation project(':gear4jtest-external-jdbc')
}

ext.moduleName = 'io.github.gear4jtest.spring.boot.starter'
