configurations {
    jaxb
}

dependencies {
    jaxb 'org.glassfish.jaxb:jaxb-xjc:4.0.2'
    jaxb 'org.glassfish.jaxb:jaxb-runtime:4.0.2'
    jaxb 'jakarta.xml.bind:jakarta.xml.bind-api:4.0.0'

    implementation project(':gear4jtest-core')
    implementation 'jakarta.xml.bind:jakarta.xml.bind-api:4.0.0'
    implementation 'org.glassfish.jaxb:jaxb-runtime:4.0.2'
    implementation 'org.eclipse.jdt:ecj:3.42.0'
    implementation group: 'com.palantir.javapoet', name: 'javapoet', version: '0.7.0'
    implementation group: 'org.eclipse.jdt', name: 'org.eclipse.jdt.core', version: '3.43.0'
    implementation group: 'org.eclipse.platform', name: 'org.eclipse.text', version: '3.14.400'
}

def generatedSourcesDir = file("${buildDir}/generated/sources/jaxb")

tasks.register('generateJaxb', JavaExec) {
    group = 'build'
    description = 'Generate Java classes from XSD schemas'

    doFirst {
        generatedSourcesDir.mkdirs()
    }

    classpath = configurations.jaxb
    mainClass = 'com.sun.tools.xjc.XJCFacade'

    args = [
            '-d', generatedSourcesDir.absolutePath,
            '-p', 'io.test.gear4jtest.xml.generated',
            '-verbose',
            '-extension',
            '-b', 'src/main/resources/bindings.xjb',
            'src/main/resources/assembly-line.xsd'
    ]

    inputs.files fileTree(dir: 'src/main/resources/xsd', include: '**/*.xsd')
    outputs.dir generatedSourcesDir
}

tasks.register('cleanGeneratedSources', Delete) {
    delete generatedSourcesDir
}

sourceSets {
    main {
        java {
            srcDirs += generatedSourcesDir
        }
    }
}

compileJava.dependsOn generateJaxb
clean.dependsOn cleanGeneratedSources

ext.moduleName = 'io.test.gear4jtest.xml'
