dependencies {
    implementation project(':gear4jtest-core')
    implementation project(':gear4jtest-external-api')

    implementation group: 'org.eclipse.jdt', name: 'org.eclipse.jdt.core', version: '3.43.0'
    implementation group: 'org.eclipse.platform', name: 'org.eclipse.text', version: '3.14.400'
}

ext.moduleName = 'io.test.gear4jtest.xml'
