pluginManagement {
    repositories {
        maven {
            url = uri(providers.gradleProperty('gear4jRepository').get())
            content {
                includeGroupByRegex 'io[.]github[.]gear4jtest([.].*)?'
            }
        }
        mavenCentral {
            content {
                excludeGroupByRegex 'io[.]github[.]gear4jtest([.].*)?'
            }
        }
    }
    plugins {
        id 'io.github.gear4jtest.xml2java' version providers.gradleProperty('gear4jVersion').get()
    }
}

dependencyResolutionManagement {
    repositories {
        maven {
            url = uri(providers.gradleProperty('gear4jRepository').get())
            content {
                includeGroupByRegex 'io[.]github[.]gear4jtest([.].*)?'
            }
        }
        mavenCentral {
            content {
                excludeGroupByRegex 'io[.]github[.]gear4jtest([.].*)?'
            }
        }
    }
}

rootProject.name = 'gear4jtest-consumer-smoke'
